- CHANGELOG.md
- lib/trackler/track.rb
- test/trackler/track_test.rb
The 'problems' method on the track was actually returning slugs.
Yeah, really confusing.
* _slug_ - the URL-friendly identifier for an exercise.
* _problem_ - the generic, language-independent metadata for an exercise.
* _implementation_ - the language-specific implementation of an exercise.
The domain concepts are decent, provided we can get all the variables and
methods named consistently.
I think the origin of the confusion was that the configuration file
refers to a number of different sets of slugs:
- active exercises in the track
- foregone exercises (which will never be implemented)
- deprecated exercises (implemented, but no longer active)
So we were referring to the full set of slugs as "slugs", and needed
something to call the thing that represents "active slugs", and since …
> Fix confusion around domain concepts.

- lib/trackler/track.rb
- test/trackler/track_test.rb
This defaults to using SVG if it's available, then falls back to assuming PNG.
This still puts the burden of finding the default Exercism icon on the caller, which we should eventually fix (serving a default icon if no track icon can be found). I'd like to use an svg for that, though, so I've not done it yet (I have a file with SVG of the logo in it, but I don't have the software to open it).
See exercism/exercism.io#2910
/cc @Insti
> Add support for SVG icons

- fixtures/common/exercises/no-metadata/description.md
- lib/trackler/problem.rb
- lib/trackler/problems.rb
- test/trackler/problem_test.rb
- test/trackler/problems_test.rb
Re-applies: https://github.com/exercism/trackler/commit/036a2a7f579aa29e4815cf32dd285105a810de0b
Fixes issues caused by x-api tests using the Trackler test fixtures.
Has been tested against the [current x-api master](https://github.com/exercism/x-api/tree/67cec8e670764a585cef16469869e85e6f07deea)
In https://github.com/exercism/trackler/commit/7bfbffe4fc1d5735db798d01ef33b08f94024b6e#commitcomment-20003912 @kytrinyx wrote: 
> Yes, this PR violated the assumption that no exercise, ever, will be missing a metadata.yml file. 
That is a reasonable assumption, and an important one so I think that Trackler should enforce this through some mechanism other than pure assumption.
Trackler now **Ignores** any exercises missing a `metadata.yml` file.
Any directory that does not contain a …
> Ignore invalid problems / Fix x-api compatability

- CHANGELOG.md
- fixtures/tracks/fake/docs/INSTALLATION.org
- lib/trackler/track.rb
- test/trackler/track_test.rb
In order to avoid hard-coding complete API paths for images, we need to add
a way to let the caller define where the documentation images can be found.
This also lets us see the images in the markdown on GitHub by defaulting to the
./docs/img path location.
It's kind of magical, but it makes a lot more sense than what we've been doing
and it makes it easier to contribute.
See exercism/exercism.io#3312
> Make documentation image paths configurable

- CHANGELOG.md
- fixtures/tracks/fake/docs/TESTS.md
- lib/trackler/track.rb
- test/trackler/track_test.rb
We don't want to substitute the default image path if a full URL is used to refer
to an image in the track documentation.
> Handle full URLs as documentation images

- fixtures/tracks/animal/.meta/include-in-fish.txt
- fixtures/tracks/animal/fish/included-via-symlink.txt
- test/trackler/implementation_test.rb
We have a use case in https://github.com/exercism/xhaskell/issues/442
where we would like to symlink files.
We have one common file that will get delivered with each exercise, and
we would only like to have to maintain one instance of it in the repo,
while symlinking it into all exercise directories.
This is a separate case than https://github.com/exercism/x-api/issues/29
because that talks about files that are not associated with any
particular exercise - their destination is a directory outside of any
exercise directory, whereas our destination is inside each exercise
directory.
For this case to work for us, we need trackler to correctly follow
symlinks present in an implementation. It currently does. In adding this
test, we request that this behaviour in the face of a symlink not …
> implementation: Test for symlinked files

- test/test_helper.rb
When generating the coverage report exclude the test case files in the /test/ directory.
> Ignore test files in coverage report.

- fixtures/tracks/animal/.meta/include-in-fish.txt
- fixtures/tracks/animal/fish/included-via-symlink.txt
- test/trackler/implementation_test.rb
The symlink test is failing for me both locally and on CI.
Reverts exercism/trackler#12
> Revert the test for symlinked files

- test/trackler/problem_test.rb
- test/trackler/track_test.rb
Fixes: #18 
Fix minitest warnings by replacing `assert_equal nil, result` with `assert_nil result`
Warnings were:
```
Use assert_nil if expecting nil from
/home/travis/build/exercism/trackler/test/trackler/problem_test.rb:82:in
`test_track_with_no_canonical_data'. This will fail in MT6.
Use assert_nil if expecting nil from
/home/travis/build/exercism/trackler/test/trackler/track_test.rb:23:in
`test_default_track'. This will fail in MT6.
Use assert_nil if expecting nil from
/home/travis/build/exercism/trackler/test/trackler/track_test.rb:148:in
`test_icon_path_nonexisting'. This will fail in MT6.
```
> Replace "assert_equal nil" with "assert_nil"

- lib/trackler/track.rb
- test/trackler/track_test.rb
Fixes #28 
The method remains backwards-compatible by still accepting the positional
argument, but the keyword argument takes highest precedence.
Setting of the default value has been moved from the arguments to the
method body, this makes the signature look slightly different, but the
functionality is the same.
The method `warn` if the positional argument is used.
> Add `image_path` keyword argument to Track#docs method.

- fixtures/tracks/fruit/SETUP.md
- fixtures/tracks/fruit/exercises/banana/HINTS.md
- lib/trackler/implementation.rb
- test/trackler/implementation_test.rb
Fixes #26
This patch places the implementation specific hints before the track specific hints in the readme of an exercise leading to a more logical ordering of information in the readme that is displayed on the exercism.io site and delivered by the cli tool.
Note:  There is some additional 'noise' in this PR due to some modifications to the fixture files to help make the problem and solution more obvious.
> Display exercise hints before track hints in Readme

- lib/trackler/problem.rb
- test/trackler/problem_test.rb
The usage of these methods was removed in https://github.com/exercism/x-api/pull/147
> Remove unused, deprecated methods

- lib/trackler/track.rb
https://github.com/exercism/trackler/pull/29#discussion_r111963141
I don't type "deprecated" correctly every time, @kytrinyx notices every time.
So I fix them and try to remember to do better next time.
I probably should put a spellcheck in my pre-commit hook.
> Minor: Fix typo in deprec(a)ted

- fixtures/tracks/animal/config.json
- fixtures/tracks/animal/exercises/dog/a_test_example_for.animal
- lib/trackler/implementation.rb
- lib/trackler/implementations.rb
- lib/trackler/track.rb
- test/trackler/implementation_test.rb
This is an alternate solution to: https://github.com/exercism/trackler/pull/32
And allows tracks to provide their own `ignore_pattern` in `config.json` which will override the default of /`example`/
This is necessary since the Go track is implementing example tests, which have example in the file name, but are not part of the reference solution.
See exercism/xgo#621
The first two commits are @kytrinyx's refactorings.
*  Inline some constants that weren't helping readability
* Change Implementation so that it is initialized with two objects (track and problem) rather than a problem object and a bunch of attributes. All the attributes exist in the track, and for the new behavior (added in the third commit) we also need the test pattern from the track.
The third is the test that @kytrinyx …
> Customizable ignore pattern

- README.md
When considering API changes it is useful to know how the gem is being used 'in the wild' so this section lists all the known users of the gem. 
It should be safe* to make changes if all these dependencies are updated as necessary.
\* this is not a guarantee
> README.md: Add links to the users of this gem.

- lib/trackler/implementation.rb
- test/trackler/implementation_test.rb
Deprecate `Implementation#files=` method
The `files=` method should not be public.
Currently is is only used by x-api to add solution files to the file bundle for the 'restore' endpoint. 
See: https://github.com/exercism/x-api/blob/master/api/v1/routes/exercises.rb#L20
This PR adds the preferred method `merge_files` and adds a deprecation warning to `files=` method
> Deprecate Implementation#files=

- lib/trackler/implementation.rb
- test/trackler/implementation_test.rb
https://github.com/exercism/x-common/pull/775 moves the first line of the description of an implementation from the blurb to the description so that the description will be self contained.
If Trackler prepends the blurb to the description when it is already there, the blurb will appear to be doubled up in the readme.
This patch checks, and does not add the blurb to the readme if it matches the start of the description text.
Addresses part 1 of Issue #42
> Suppress blurb if it starts the description

- lib/trackler.rb
- lib/trackler/implementation.rb
- lib/trackler/implementations.rb
- lib/trackler/track.rb
- test/trackler/implementation_test.rb
- test/trackler/implementations_test.rb
- test/trackler/track_test.rb
An `Implementation` is a `Problem`
By using composition we delegate all Problem methods to the Problem instance variable that an Implementation maintains.
This simplifies usage as users can now `implementation.slug` instead of `implementation.problem.slug` as before.
These are the public methods that an Implementation instance adds:
`[:files, :files=, :git_url, :problem, :readme, :track_id, :zip]`
Also a few refactorings in the `implementation.rb` file.
Note: The `problem` method is deprecated and will emit a `warn`ing on use.
Possibly controversial:
`Track#problems` is deprecated in favour of `Track#implementations` and will emit a warning on use.
> An `Implementation` is a `Problem`

- lib/trackler/implementation.rb
- test/trackler/implementation_test.rb
The default `dup` or `clone` behaviour is to make a shallow copy.
This provides a deep copy of the `files` instance variable as well so when they are modified
by `merge_files` the original will remain unchanged.
Thanks to @petertseng for bringing this to my attention and doing some detective work as to the cause.
Ref: https://github.com/exercism/trackler/pull/39#issuecomment-303578961
> Make Implementation#dup also dup @files

- lib/trackler/implementation.rb
- test/trackler/implementation_test.rb
The information in the blurb has been incorporated into the description, so no longer needs to be added to it when building the readme.
Ref: https://github.com/exercism/x-common/pull/775
Closes: https://github.com/exercism/trackler/issues/42
> No longer add blurb to readme

- lib/trackler/implementation.rb
- test/trackler/implementation_test.rb
This method will return the English representation of the language that the exercise is implemented in.
Note: This is NOT the track ID/slug, which you should never need to ask the Implementation for.
See: #47
> Add Implementation#language method.

- lib/trackler/implementation.rb
- test/trackler/implementation_test.rb
Being able to mutate the files leads to bugs where the files you think you have are not the files you actually have.
Remove the temptation to ever do this by removing support for it.
The removed methods `#files=`, `merge_files` are both now unused since (x-api) was rewritten to avoid them.
Fixes: #52
> Remove ability to mutate Implementation#@files

- lib/trackler/implementation.rb
- test/trackler/implementation_test.rb
Now that we've sorted out our terminology, we were using 'Problem'
wrong in our message about submitting incomplete solutions.
See https://github.com/exercism/discussions/issues/145
/cc @Insti
> Fix wording in assembled exercise READMEs

- lib/trackler/track.rb
- test/trackler/track_test.rb
`track.rb` previously showed 100% coverage, but several methods were only tested incidentally by the tests of other classes. 
This PR ensures that `track_test.rb` completely covers the `track.rb` file.
> 100% test coverage for track.rb

- fixtures/tracks/animal/config.json
- fixtures/tracks/fake/config.json
- fixtures/tracks/fruit/config.json
- fixtures/tracks/jewels/config.json
- fixtures/tracks/shoes/config.json
- fixtures/tracks/snowflake/config.json
- lib/trackler/track.rb
The deprecated "problems" key in the `config.json` is no longer used by the real tracks, 
they all use the "exercises" key.
Ref exercism/meta#4
> Remove support for config.json "problems" key

- lib/trackler.rb
- lib/trackler/problem.rb
- lib/trackler/problems.rb
- test/trackler_test.rb
The downstream dependencies no longer rely on these, referring
instead to the Specification(s) classes.
Closes #40
> Delete the Problem(s) classes

- fixtures/tracks/animal/SETUP.md
- fixtures/tracks/animal/exercises/TRACK_HINTS.md
- fixtures/tracks/fruit/SETUP.md
- fixtures/tracks/jewels/exercises/TRACK_HINTS.md
- lib/trackler/track.rb
- test/trackler/implementation_test.rb
- test/trackler/track_test.rb
There was a cascade of renames over the past few years, and we finally found a name we like.
We've updated all the language track repositories to rename the file to the name we decided on,
which lets us remove a bit of cruft.
Yay.
This closes https://github.com/exercism/meta/issues/5
> Delete support for deprecated readme insert filenames

- lib/trackler/track.rb
- test/trackler/track_test.rb
The downstream dependencies all use the keyword argument for the image_path. /cc @Insti
> Remove deprecated positional argument for track docs

- fixtures/tracks/fake/docs/STRAY.md
- lib/trackler/doc_file.rb
- lib/trackler/track.rb
- test/trackler/doc_file_test.rb
The files in 'docs' could be either markdown or orgmode. This finds whatever is present
even if there is a mix.
This leaves a dirty hack for the EXERCISE_README_INSERT fallback, which
I think is fine since we're just about ready to remove it per
https://github.com/exercism/meta/issues/5
Fixes #64
> Add generic support for orgmode doc files

- lib/trackler/doc_file.rb
- test/trackler/doc_file_test.rb
I should have caught this. These should be within the Trackler module, not
top-level constants.
> Namespace the docfiles

- lib/trackler/track.rb
I'm not sure how I left this in.
It was part of a large refactoring. I suspect that this method had a number of changes where earlier on it made sense to have a variable, and then when it no longer did I didn't notice.
> Delete stray assignment

- test/test_helper.rb
The test helper is referencing the PROCESS_ID global variable, which is defined by the English
library.
> Require english library before running tests

- fixtures/tracks/fake/exercises/two/README.md
- lib/trackler/implementation.rb
- test/trackler/implementation_test.rb
This allows us to hook into the new exercise READMEs that get generated from configlet. See https://github.com/exercism/meta/issues/15
> Use static exercise README if it is present

- lib/trackler/track.rb
- test/trackler/track_test.rb
Use an object instead of a hash when parsing the config.json file.
We could use forwarding, but there are enough places where we want to add a default value that I didn't bother.
> Refactor the track config
